#!/usr/bin/env node
// Copies the third-party assets the app used to load from CDNs into
// this repo, so the app (web AND native) has no runtime CDN dependency:
//   - the Supabase browser bundle  -> vendor/supabase.js
//   - Tajawal / Aref Ruqaa / Amiri Quran web fonts -> fonts/ + fonts/fonts.css
//
// Run after installing the build-time packages (see the setup steps):
//   npm install -D --save-exact @supabase/supabase-js
//   npm install -D @fontsource/tajawal @fontsource/aref-ruqaa @fontsource/amiri-quran
//   npm run vendor
//
// Safe to re-run — vendor/ and fonts/ are fully regenerated each time.
// COMMIT the generated vendor/ and fonts/ folders: the GitHub Pages site
// (which serves the repo root directly) needs them too.

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const NODE_MODULES = path.join(ROOT, "node_modules");
const VENDOR_DIR = path.join(ROOT, "vendor");
const FONTS_DIR = path.join(ROOT, "fonts");

// Same families/weights the old Google Fonts <link> requested.
const FONTS = [
  { pkg: "tajawal", weights: [400, 500, 700, 900] },
  { pkg: "aref-ruqaa", weights: [400, 700] },
  { pkg: "amiri-quran", weights: [400] },
];
// Arabic glyphs for the Quran/UI text; latin for digits, "XP", "VS", etc.
const SUBSETS = ["arabic", "latin"];

function fail(msg) {
  console.error("\nError: " + msg + "\n");
  process.exit(1);
}

function vendorSupabase() {
  const pkgDir = path.join(NODE_MODULES, "@supabase", "supabase-js");
  if (!fs.existsSync(pkgDir)) {
    fail("@supabase/supabase-js is not installed. Run:  npm install -D --save-exact @supabase/supabase-js");
  }
  const umdDir = path.join(pkgDir, "dist", "umd");
  const file = ["supabase.min.js", "supabase.js"].find((f) => fs.existsSync(path.join(umdDir, f)));
  if (!file) {
    fail(`No UMD bundle found in ${umdDir}. This Supabase version may have moved its browser build — tell me what's in that folder.`);
  }

  fs.rmSync(VENDOR_DIR, { recursive: true, force: true });
  fs.mkdirSync(VENDOR_DIR, { recursive: true });
  fs.copyFileSync(path.join(umdDir, file), path.join(VENDOR_DIR, "supabase.js"));

  const version = JSON.parse(fs.readFileSync(path.join(pkgDir, "package.json"), "utf8")).version;
  console.log(`vendor/supabase.js  <- @supabase/supabase-js@${version} (${file})`);
}

function vendorFonts() {
  fs.rmSync(FONTS_DIR, { recursive: true, force: true });
  fs.mkdirSync(FONTS_DIR, { recursive: true });

  let css = "/* GENERATED by scripts/vendor.js from @fontsource — do not edit by hand. */\n";
  let fileCount = 0;

  for (const { pkg, weights } of FONTS) {
    const pkgDir = path.join(NODE_MODULES, "@fontsource", pkg);
    if (!fs.existsSync(pkgDir)) {
      fail(`@fontsource/${pkg} is not installed. Run:  npm install -D @fontsource/${pkg}`);
    }
    const outFilesDir = path.join(FONTS_DIR, pkg, "files");
    fs.mkdirSync(outFilesDir, { recursive: true });

    for (const subset of SUBSETS) {
      for (const weight of weights) {
        const cssFile = path.join(pkgDir, `${subset}-${weight}.css`);
        if (!fs.existsSync(cssFile)) {
          // Not every family ships every subset/weight; only the Arabic
          // ones are essential.
          if (subset === "arabic") fail(`Missing ${subset}-${weight}.css in @fontsource/${pkg}.`);
          console.warn(`  (skipping ${pkg} ${subset} ${weight}: not shipped by this package)`);
          continue;
        }

        let text = fs.readFileSync(cssFile, "utf8");
        // Drop the legacy .woff fallback — every WebView we target does woff2.
        text = text.replace(/,\s*url\([^)]*\.woff\)\s*format\(['"]woff['"]\)/g, "");
        text = text.replace(/\/\*[\s\S]*?\*\//g, "").trim(); // strip fontsource's own comments

        const woff2Names = [...text.matchAll(/url\(\.\/files\/([^)]+\.woff2)\)/g)].map((m) => m[1]);
        if (!woff2Names.length) fail(`No woff2 url found in ${cssFile} — its format may have changed.`);
        for (const name of woff2Names) {
          const from = path.join(pkgDir, "files", name);
          if (!fs.existsSync(from)) fail(`${from} referenced by ${cssFile} but not found.`);
          fs.copyFileSync(from, path.join(outFilesDir, name));
          fileCount++;
        }

        text = text.replace(/url\(\.\/files\//g, `url(./${pkg}/files/`);
        css += `\n/* ${pkg} ${subset} ${weight} */\n${text}\n`;
      }
    }
  }

  fs.writeFileSync(path.join(FONTS_DIR, "fonts.css"), css, "utf8");

  // Sanity check: every url() in the generated CSS must exist on disk.
  for (const m of css.matchAll(/url\(([^)]+)\)/g)) {
    const rel = m[1].replace(/['"]/g, "");
    if (!fs.existsSync(path.join(FONTS_DIR, rel))) fail(`fonts.css points at missing file: ${rel}`);
  }
  console.log(`fonts/fonts.css     <- ${fileCount} woff2 files`);
}

vendorSupabase();
vendorFonts();
console.log("\nDone. Commit vendor/ and fonts/ along with everything else.");
